<a href="https://colab.research.google.com/github/golammostafa13/hate_speech_detection/blob/main/bangla_hate_speech_machine_learning_classifiers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import and Dataset load

In [ ]:
import pandas as pd
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot,Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Dense , Flatten ,Embedding,Input,LSTM, Bidirectional, Dense, Dropout,GRU,SpatialDropout1D, Conv1D
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.preprocessing.text import text_to_word_sequence
from tensorflow.keras.initializers import Constant
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
file = '/content/drive/MyDrive/Paper Writing/cleaned_data.csv'
data = pd.read_csv(file, encoding='utf-8')

In [ ]:
data.head()

Unnamed: 0                                           sentence  hate  \
0           0                     যত্তসব পাপন শালার ফাজলামী!!!!!     1   
1           1                  পাপন শালা রে রিমান্ডে নেওয়া দরকার     1   
2           2  জিল্লুর রহমান স্যারের ছেলে এতো বড় জারজ হবে এটা...     1   
3           3                শালা লুচ্চা দেখতে পাঠার মত দেখা যায়     1   
4           4   তুই তো শালা গাজা খাইছচ।তুর মার হেডায় খেলবে সাকিব     1   

  category                                       cleaned_text  sentenceLength  \
0   sports                     যত্তসব পাপন শালার ফাজলামী                    4   
1   sports                  পাপন শালা রে রিমান্ডে নেওয়া দরকার               6   
2   sports  জিল্লুর রহমান স্যারের ছেলে এতো বড় জারজ হবে এটা...              20   
3   sports                শালা লুচ্চা দেখতে পাঠার মত দেখা যায়               7   
4   sports   তুই তো শালা গাজা খাইছচ তুর মার হেডায় খেলবে সাকিব              10   

   ReviewChars  
0           30  
1           33  
2          107  
3           35  
4           48

# Machine Learning Classifiers

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import accuracy_score

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data['cleaned_text'], data['hate'],random_state = 0,test_size = 0.20)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((24000,), (6000,), (24000,), (6000,))

In [ ]:
Tfidf_vect = TfidfVectorizer(max_features=4000)
Tfidf_vect.fit(data['cleaned_text'])
Train_X_Tfidf = Tfidf_vect.transform(X_train)
Test_X_Tfidf = Tfidf_vect.transform(X_test)

In [ ]:
model = MultinomialNB()
model.fit(Train_X_Tfidf,y_train)
from sklearn.metrics import accuracy_score

predictions_train_NB = model.predict(Train_X_Tfidf)
predictions_NB = model.predict(Test_X_Tfidf)
print("Naive Bayes Training Accuracy Score -> ",accuracy_score(predictions_train_NB, y_train)*100)
print("Naive Bayes Test Accuracy Score -> ",accuracy_score(predictions_NB, y_test)*100)

Naive Bayes Training Accuracy Score ->  74.75
Naive Bayes Test Accuracy Score ->  73.33333333333333


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test,predictions_NB))
print(confusion_matrix(y_test,predictions_NB))

              precision    recall  f1-score   support

           0       0.73      0.96      0.83      4021
           1       0.76      0.28      0.41      1979

    accuracy                           0.73      6000
   macro avg       0.74      0.62      0.62      6000
weighted avg       0.74      0.73      0.69      6000

[[3844  177]
 [1423  556]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier

RF=RandomForestClassifier(n_estimators=100)
RF.fit(Train_X_Tfidf,y_train)
pred_y_train = RF.predict(Train_X_Tfidf)
pred_y = RF.predict(Test_X_Tfidf)
# Use accuracy_score function to get the accuracy
print("Train Accuracy Score -> ",accuracy_score(pred_y_train, y_train)*100)
print("Test Accuracy Score -> ",accuracy_score(pred_y, y_test)*100)

Train Accuracy Score ->  94.55
Test Accuracy Score ->  73.88333333333334


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,pred_y))
cf_matrix = confusion_matrix(y_test, pred_y)
print(cf_matrix)

              precision    recall  f1-score   support

           0       0.75      0.92      0.83      4021
           1       0.70      0.37      0.48      1979

    accuracy                           0.74      6000
   macro avg       0.72      0.65      0.65      6000
weighted avg       0.73      0.74      0.71      6000

[[3702  319]
 [1248  731]]


In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()

clf = clf.fit(Train_X_Tfidf,y_train)

pred_y_train = clf.predict(Train_X_Tfidf)
pred_y = clf.predict(Test_X_Tfidf)
# Use accuracy_score function to get the accuracy
print("Train Accuracy Score -> ",accuracy_score(pred_y_train, y_train)*100)
print("Test Accuracy Score -> ",accuracy_score(pred_y, y_test)*100)

Train Accuracy Score ->  94.55
Test Accuracy Score ->  68.7


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,pred_y))
cf_matrix = confusion_matrix(y_test, pred_y)
print(cf_matrix)

              precision    recall  f1-score   support

           0       0.75      0.80      0.77      4021
           1       0.53      0.45      0.49      1979

    accuracy                           0.69      6000
   macro avg       0.64      0.63      0.63      6000
weighted avg       0.68      0.69      0.68      6000

[[3230  791]
 [1087  892]]


In [ ]:
from sklearn import svm
SVM = svm.SVC(C=1.0, kernel='linear', degree=3, gamma='auto')
SVM.fit(Train_X_Tfidf,y_train)
pred_y_train = SVM.predict(Train_X_Tfidf)
pred_y = SVM.predict(Test_X_Tfidf)
# Use accuracy_score function to get the accuracy
print("SVM Train Accuracy Score -> ",accuracy_score(pred_y_train, y_train)*100)
print("SVM Test Accuracy Score -> ",accuracy_score(pred_y, y_test)*100)

SVM Train Accuracy Score ->  76.27916666666667
SVM Test Accuracy Score ->  75.38333333333334
